#!/bin/bash
set -euo pipefail

year=$(date +%Y)
files=$(git diff --cached --name-only)

# check code style
git diff --cached --diff-filter=ACM -- '*.c' '*.h' | \
	./scripts/checkpatch.pl --no-tree --ignore ELSE_AFTER_BRACE,SPDX_LICENSE_TAG -

# check code style for C++ files
cpp_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cc|cpp|hh|hpp|h)$' | grep -v 'clickhouse-cpp')
if [ -n "$cpp_files" ]; then
    for file in $cpp_files; do
        ./scripts/run-clang-tidy.sh "$file"
    done
fi

# update copyrights
perl -i -pe "s/Copyright \(C\) (\d{4})(-\d{4})? Tempesta/Copyright \(C\) \$1-$year Tempesta/g" $files
perl -i -pe "s/Copyright \(C\) $year-$year Tempesta/Copyright \(C\) $year Tempesta/g" $files

git add $files
