listen 10.0.2.15:443 proto=h2;
listen 10.0.2.15:80;

frang_limits {
	http_methods GET HEAD;
	http_uri_len 1000;
}

block_action attack reply;
block_action error reply;

srv_group default {
	server 185.8.106.163:80;
}

vhost tempesta-tech.com {
	tls_certificate /home/evgeny/workdir/certs/tempesta-tech.test.crt;
        tls_certificate_key /home/evgeny/workdir/certs/tempesta-tech.test.key;
	tls_tickets secret="f00)9eR59*_/22" lifetime=7200;

	resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

	proxy_pass default;
}

cache 1;
cache_fulfill * *;

http_chain redirection_chain {
	uri == "/blog"		-> 301 = /blog/1;
	uri == "/blog/"		-> 301 = /blog/1;
	uri == "/services"	-> 301 = /development-services;
	uri == "/services.html"	-> 301 = /development-services;
	uri == "/c++-services"	-> 301 = /development-services;
	uri == "/index.html"	-> 301 = /index;
	uri == "/company.html"	-> 301 = /company;
	uri == "/blog/fast-programming-languages-c-c++-rust-assembly" -> 301 = /blog/fast-programming-languages-c-cpp-rust-assembly;

	-> tempesta-tech.com;
}

http_chain {
	host == "tempesta-tech.com" -> redirection_chain;
}
