#!/bin/bash
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

dir="$(dirname $0)"

. "$dir"/info

for file in "$dir"/include-*; do
  name="$(echo $file | sed -e 's,^.*/include-,,')"
  hooks+=($name)
  . "$file"
done

if [ "$RELEASE" == "$(uname -r)" ]; then
  running_ver="$(uname -v)"
  running_ver="${running_ver#* $DISTRIBUTOR }"
  running_ver="${running_ver%% *}"
  if [ "$running_ver" != "$SOURCEVERSION" ]; then
    cat <<EOF
You have installed version $PACKAGE_VERSION of
$PACKAGE_NAME, but version $running_ver is currently
running.

You should reboot to complete the upgrade.  Until you do this, some
modules may fail to load.  This is NOT a bug.

If you have already rebooted, check your boot loader configuration.

EOF
    yesno "Do you still want to report a bug? " nop
    if [ "$REPLY" = nop ]; then
      exit 1
    fi
  fi
  for hook in ${hooks[@]}; do
    add_$hook
  done
else
  yesno "Does the bug you are reporting affect this computer? " yep
  same_system=$REPLY
  for hook in ${hooks[@]}; do
    ask_$hook
  done
fi
